module.exports = {
  MONGO_DB: process.env.MONGO_DB,
  SECRET: process.env.SECRET,
  CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
  CLOUDINARY_SECRET: process.env.CLOUDINARY_SECRET,
  CLOUDINARY_NAME: process.env.CLOUDINARY_NAME,
  GOOGLE_MAP_KEY: process.env.GOOGLE_MAP_KEY,
  EMAIL_SERVICE: process.env.EMAIL_SERVICE,
  PASSWORD_EMAIL_SERVICE: process.env.PASSWORD_EMAIL_SERVICE
};
